//
// Created by william on 2021/8/15.
//

#ifndef CROSS_PLATFORM_DEMO_DESCRIPTORSETLAYOUT_H
#define CROSS_PLATFORM_DEMO_DESCRIPTORSETLAYOUT_H

class DescriptorSetLayout
{
};

#endif //CROSS_PLATFORM_DEMO_DESCRIPTORSETLAYOUT_H
