//
// Created by william on 2021/8/15.
//

#ifndef CROSS_PLATFORM_DEMO_DESCRIPTORSET_H
#define CROSS_PLATFORM_DEMO_DESCRIPTORSET_H

class DescriptorSet
{
};

#endif //CROSS_PLATFORM_DEMO_DESCRIPTORSET_H
