//
// Created by william on 2021/8/15.
//

#ifndef CROSS_PLATFORM_DEMO_PIPELINESTATE_H
#define CROSS_PLATFORM_DEMO_PIPELINESTATE_H

class PipelineState
{
};

#endif //CROSS_PLATFORM_DEMO_PIPELINESTATE_H
